#!/usr/bin/env node
// Static-site builder for UtilPlex.
//   1. Reads content/{site,tools,patch-notes,pages/*}.json
//   2. Renders Eta templates → site/<path>/index.html
//   3. Bundles tools/src/<entry>.js → site/assets/tools/<entry>.js with esbuild
//   4. Runs Tailwind v4 over builder/assets/app.css → site/assets/app.css
//   5. Copies static assets and writes sitemap.xml, rss.xml, robots.txt

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Eta } from "eta";
import postcss from "postcss";
import tailwindcss from "@tailwindcss/postcss";
import * as esbuild from "esbuild";

import { ICONS, icon } from "./lib/icons.mjs";
import { homeGraph, toolGraph, webPageJsonLd } from "./lib/seo.mjs";
import { buildSitemap } from "./lib/sitemap.mjs";
import { buildPatchNotesRss } from "./lib/rss.mjs";
import { formatDate, minifyCss, minifyHtml } from "./lib/util.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CONTENT = path.join(ROOT, "content");
const SITE = path.join(ROOT, "site");
const TEMPLATES = path.join(__dirname, "templates");
const ASSETS = path.join(__dirname, "assets");
const TOOLS_SRC = path.join(ROOT, "tools", "src");

async function readJson(file) {
  return JSON.parse(await fs.readFile(file, "utf8"));
}
async function writeFile(file, contents) {
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, contents);
}
async function readDirJson(dir) {
  let entries = [];
  try { entries = await fs.readdir(dir); } catch { return []; }
  const out = [];
  for (const name of entries) {
    if (!name.endsWith(".json")) continue;
    out.push(await readJson(path.join(dir, name)));
  }
  return out;
}

async function clearSite() {
  await fs.mkdir(SITE, { recursive: true });
  for (const entry of await fs.readdir(SITE)) {
    const p = path.join(SITE, entry);
    try {
      await fs.rm(p, { recursive: true, force: true, maxRetries: 5, retryDelay: 100 });
    } catch (e) {
      // npm run preview may hold files open on Windows / WSL; safe to skip
      if (["EBUSY", "EACCES", "EPERM"].includes(e.code)) continue;
      throw e;
    }
  }
}

async function buildCss() {
  const inputPath = path.join(ASSETS, "app.css");
  const input = await fs.readFile(inputPath, "utf8");
  const result = await postcss([tailwindcss()]).process(input, {
    from: inputPath,
    to: path.join(SITE, "assets", "app.css"),
    map: false,
  });
  return minifyCss(result.css);
}

async function buildToolBundles(entries) {
  if (!entries.length) return;
  await fs.mkdir(path.join(SITE, "assets", "tools"), { recursive: true });
  // Bundle them all in one esbuild call. Splitting=false so each entry is
  // self-contained and the browser only fetches a single file per page.
  const result = await esbuild.build({
    entryPoints: entries.map(e => ({
      in: path.join(TOOLS_SRC, `${e}.js`),
      out: e,
    })),
    bundle: true,
    minify: true,
    format: "esm",
    target: ["es2020"],
    outdir: path.join(SITE, "assets", "tools"),
    logLevel: "warning",
    legalComments: "none",
    treeShaking: true,
  });
  if (result.errors.length) throw new Error("esbuild failed");
  return result.metafile;
}

async function copyStatic() {
  await fs.mkdir(path.join(SITE, "assets"), { recursive: true });
  await fs.copyFile(path.join(ASSETS, "main.js"), path.join(SITE, "assets", "main.js"));

  // Logo variants — generated by `npm run optimize-logo`. Skipped silently
  // if the optimizer hasn't been run yet so a fresh checkout still builds.
  const variants = [
    ["logo-32.png",       "favicon-32.png"],
    ["logo-180.png",      "apple-touch-icon.png"],
    ["logo-192.png",      "icon-192.png"],
    ["logo-512.png",      "icon-512.png"],
    ["logo-64.png",       "assets/logo.png"],
    ["logo-64.webp",      "assets/logo.webp"],
    ["logo-hero.png",     "assets/logo-hero.png"],
    ["logo-hero.webp",    "assets/logo-hero.webp"],
    ["logo-hero@2x.png",  "assets/logo-hero@2x.png"],
    ["logo-hero@2x.webp", "assets/logo-hero@2x.webp"],
    ["og-image.png",      "assets/og-image.png"],
  ];
  for (const [src, dst] of variants) {
    const from = path.join(ASSETS, src);
    try {
      await fs.mkdir(path.dirname(path.join(SITE, dst)), { recursive: true });
      await fs.copyFile(from, path.join(SITE, dst));
    } catch (e) {
      if (e.code !== "ENOENT") throw e;
    }
  }

  // Web app manifest — surfaces the larger PNG icons to Android/PWA UIs.
  const manifest = {
    name: "UtilPlex",
    short_name: "UtilPlex",
    description: "Fast, private developer utilities. Everything runs in your browser.",
    start_url: "/",
    display: "browser",
    background_color: "#0d1117",
    theme_color: "#0d1117",
    icons: [
      { src: "/favicon-32.png",   sizes: "32x32",   type: "image/png" },
      { src: "/icon-192.png",     sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png",     sizes: "512x512", type: "image/png" },
    ],
  };
  await fs.writeFile(path.join(SITE, "site.webmanifest"), JSON.stringify(manifest));
}

async function loadThemeInit() {
  return await fs.readFile(path.join(ASSETS, "theme-init.js"), "utf8");
}

// ---------------------------------------------------------------------------

async function main() {
  const t0 = Date.now();
  console.log("Building UtilPlex…");

  const site = await readJson(path.join(CONTENT, "site.json"));
  const tools = await readJson(path.join(CONTENT, "tools.json"));
  const patchNotes = await readJson(path.join(CONTENT, "patch-notes.json"));
  const pages = await readDirJson(path.join(CONTENT, "pages"));

  await clearSite();
  await copyStatic();

  const eta = new Eta({ views: TEMPLATES, cache: true, autoEscape: false });
  const themeInit = await loadThemeInit();
  const baseUrl = site.url.replace(/\/$/, "");

  function renderLayout(opts) {
    return eta.render("layout", {
      site,
      icon,
      themeInit,
      baseUrl,
      pageTitle: opts.pageTitle,
      pageDescription: opts.pageDescription || site.description,
      keywords: opts.keywords || "",
      canonicalUrl: baseUrl + opts.canonicalPath,
      ogType: opts.ogType || "website",
      ogImage: opts.ogImage || "",
      bodyClass: opts.bodyClass || "",
      jsonLd: opts.jsonLd || null,
      toolEntry: opts.toolEntry || null,
      robots: opts.robots || null,
      body: opts.body,
    });
  }

  // ── Home ────────────────────────────────────────────────────────────────
  {
    const body = eta.render("home", { site, categories: tools.categories, icon });
    const html = renderLayout({
      pageTitle: `${site.title} — ${site.tagline}`,
      pageDescription: site.description,
      keywords: tools.categories.flatMap(c => c.tools).flatMap(t => t.keywords || []).slice(0, 30).join(", "),
      canonicalPath: "/",
      bodyClass: "home",
      jsonLd: homeGraph({ site, baseUrl, categories: tools.categories }),
      body,
    });
    await writeFile(path.join(SITE, "index.html"), minifyHtml(html));
  }

  // ── Tools ───────────────────────────────────────────────────────────────
  const toolEntries = [];
  for (const cat of tools.categories) {
    for (const tool of cat.tools) {
      const toolBody = eta.render(`tool-bodies/${tool.entry}`, toolBodyContext(tool));
      const body = eta.render("tool", { category: cat, tool, toolBody, icon });
      const canonicalPath = `/${cat.slug}/${tool.slug}/`;
      const html = renderLayout({
        pageTitle: `${tool.title} · ${site.title}`,
        pageDescription: tool.description,
        keywords: (tool.keywords || []).join(", "),
        canonicalPath,
        bodyClass: `tool tool-${cat.slug}`,
        toolEntry: tool.entry,
        jsonLd: toolGraph({ site, baseUrl, category: cat, tool, canonical: baseUrl + canonicalPath }),
        body,
      });
      await writeFile(path.join(SITE, cat.slug, tool.slug, "index.html"), minifyHtml(html));
      toolEntries.push(tool.entry);
    }
  }
  console.log(`  ${toolEntries.length} tool pages`);

  // ── Static pages (how-it-works etc.) ───────────────────────────────────
  for (const pg of pages) {
    const body = eta.render("page", { page: pg });
    const canonicalPath = `/${pg.slug}/`;
    const html = renderLayout({
      pageTitle: `${pg.title} · ${site.title}`,
      pageDescription: pg.description || site.description,
      canonicalPath,
      bodyClass: "page",
      jsonLd: webPageJsonLd({ site, page: pg, canonical: baseUrl + canonicalPath, baseUrl }),
      body,
    });
    await writeFile(path.join(SITE, pg.slug, "index.html"), minifyHtml(html));
  }
  console.log(`  ${pages.length} static pages`);

  // ── 404 ─────────────────────────────────────────────────────────────────
  {
    // Surface a small "popular tools" grid so a wrong link still lands the
    // visitor somewhere useful. Picks the first tool in each of the first
    // four categories — broad coverage without overwhelming the page.
    const featured = tools.categories.slice(0, 4).map(c => {
      const t = c.tools[0];
      return { ...t, path: `/${c.slug}/${t.slug}/` };
    });
    const body = eta.render("404", { featured, icon });
    const html = renderLayout({
      pageTitle: `404 · ${site.title}`,
      pageDescription: "The page you're looking for doesn't exist. Browse the UtilPlex tool catalog for formatters, converters, encoders, generators, diffs, and time-zone tools.",
      canonicalPath: "/404.html",
      bodyClass: "not-found",
      // 404s should never get indexed — they're an error state, not a page.
      robots: "noindex, follow",
      body,
    });
    await writeFile(path.join(SITE, "404.html"), minifyHtml(html));
  }

  // ── Patch notes ─────────────────────────────────────────────────────────
  {
    const body = eta.render("patch-notes", {
      entries: patchNotes.entries,
      formatDate: d => formatDate(d, site.locale),
    });
    const html = renderLayout({
      pageTitle: `Patch Notes · ${site.title}`,
      pageDescription: "Recent changes and improvements to UtilPlex — new tools, bug fixes, performance work, and design updates. Subscribe to the RSS feed to follow updates.",
      canonicalPath: "/patch-notes/",
      bodyClass: "patch",
      jsonLd: webPageJsonLd({
        site,
        page: { title: "Patch Notes", description: "Recent changes and improvements to UtilPlex — new tools, bug fixes, performance work, and design updates. Subscribe to the RSS feed to follow updates." },
        canonical: baseUrl + "/patch-notes/",
        baseUrl,
      }),
      body,
    });
    await writeFile(path.join(SITE, "patch-notes", "index.html"), minifyHtml(html));
  }

  // ── Bundle tools ────────────────────────────────────────────────────────
  console.log("  bundling tools…");
  await buildToolBundles(toolEntries);

  // ── CSS ─────────────────────────────────────────────────────────────────
  console.log("  running tailwind…");
  const css = await buildCss();
  await fs.writeFile(path.join(SITE, "assets", "app.css"), css);
  console.log(`  wrote ${(css.length / 1024).toFixed(1)} KB CSS`);

  // ── sitemap / rss / robots ─────────────────────────────────────────────
  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    { path: "/", priority: "1.0", changefreq: "weekly" },
    { path: "/how-it-works/", priority: "0.5", changefreq: "monthly" },
    { path: "/patch-notes/", priority: "0.6", changefreq: "weekly" },
    ...tools.categories.flatMap(c =>
      c.tools.map(t => ({ path: `/${c.slug}/${t.slug}/`, priority: "0.8", changefreq: "monthly" }))
    ),
  ].map(u => ({ ...u, lastmod: today }));
  await fs.writeFile(path.join(SITE, "sitemap.xml"), buildSitemap({ baseUrl, urls }));

  const rss = buildPatchNotesRss({ site, baseUrl, entries: patchNotes.entries });
  await fs.writeFile(path.join(SITE, "rss.xml"), rss);

  await fs.writeFile(
    path.join(SITE, "robots.txt"),
    `User-agent: *\nAllow: /\nSitemap: ${baseUrl}/sitemap.xml\n`,
  );

  console.log(`Done in ${((Date.now() - t0) / 1000).toFixed(1)}s → site/`);
}

// ---------------------------------------------------------------------------
// Per-tool body context — small per-entry tweaks for the YAML/JSON converter
// labels. Everything else uses the tool's own template directly.
function toolBodyContext(tool) {
  const ctx = { icon, tool };
  if (tool.entry === "convert-json-yaml") {
    ctx.inputLabel = "JSON Input";
    ctx.outputLabel = "YAML Output";
  } else if (tool.entry === "convert-yaml-json") {
    ctx.inputLabel = "YAML Input";
    ctx.outputLabel = "JSON Output";
  }
  return ctx;
}

main().catch(err => { console.error(err); process.exit(1); });
